const appleCareDict = {
    "Computer": {
        "AppleCare+ iMac and Pro": {code: "S9688Z/A"},
        "AppleCare+ Mac Mini": {code: "S9703Z/A"},
        "AppleCare+ Mac Pro": {code: "S9718Z/A"},
        "AppleCare+ Mac Studio": {code: "SELQ2Z/A"},
        "AppleCare+ MacBook Air": {code: "S9788Z/A"},
        "AppleCare+ MacBook Air M2": {code: "SF8C2Z/A"},
        "AppleCare+ 13in MacBook Pro M1": {code: "S9736Z/A"},
        "AppleCare+ 13in MacBook Pro M2": {code: "SF932Z/A"},
        "AppleCare+ 14in MacBook Pro": {code: "SCPG2Z/A"},
        "AppleCare+ 16in MacBook Pro M1": {code: "SDYP2Z/A"},
        "AppleCare+ 14in MacBook M2": {code: "SGAQ2Z/A"},
        "AppleCare+ 16in MacBook Pro M2": {code: "SGCT2Z/A"},
        "AppleCare+ Mac Mini M2": {code: "SGQQ2Z/A"},    
    },
    "IPad": {
        "AppleCare+ iPad 9th gen": {code: "SCM32Z/A"},
        "AppleCare+ iPad mini 6th gen": {code: "SCLH2Z/A"},
        "AppleCare+ iPad Air 10.9in 4th gen": {code: "S8622Z/A"},
        "AppleCare+ 10.2in ipad Pro 9th gen": {code: "SCM32Z/A"},
        "AppleCare+ 10.5in ipad Pro": {code: "S8402Z/A"},
        "AppleCare+ 11in ipad Pro": {code: "S8403Z/A"},
        "AppleCare+ 12.9in ipad Pro 4th gen": {code: "S8404Z/A"},
        "AppleCare+ 12.9in ipad Pro 5th gen": {code: "S9865Z/A"},
        "AppleCare+ iPad 10th gen": {code: "SGFC2Z/A"},
        "AppleCare+ iPad Pro 11in 4th gen": {code: "SGG22Z/A"},
        "AppleCare+ iPad Pro 12.9in 6th gen": {code: "SGGY2Z/A"},    
    },
    "Audiovisual": {
        "AppleCare+ Apple TV": {code: "S9634Z/A"},
        "AppleCare+ Headphones - AirPods": {code: "S9066Z/A"},
        "AppleCare+ Headphones - AirPods Pro": {code: "S9078Z/A"},
        "AppleCare+ Headphones - AirPods Max": {code: "S9086Z/A"},
        "AppleCare+ Headphones - Beats": {code: "S9094Z/A"},    
    },
    "Watch": {
        "AppleCare+ Apple Watch Series 7 Aluminum": {code: "SCCU2Z/A"},
        "AppleCare+ Apple Watch Series 8 Aluminum": {code: "SG1L2Z/A"},
        "AppleCare+ Apple Watch SE 2nd gen": {code: "SG282Z/A"},
        "AppleCare+ Apple Watch Series 8 Stainless": {code: "SG2L2Z/A"},
        "AppleCare+ Apple Watch Ultra Titanium": {code: "SG2U2Z/A"},    
    },
};
